import { Router } from "express";
import systemRoutes from "../../../modules/system/system.routes.js";
import authRoutes from "../../../modules/auth/auth.routes.js";
import vendorsRoutes from "../../../modules/vendors/vendors.routes.js";
import customersRoutes from "../../../modules/customers/customers.routes.js";
import categoriesRoutes from "../../../modules/products/categories.routes.js";
import productsRoutes from "../../../modules/products/products.routes.js";
import ordersRoutes from "../../../modules/orders/orders.routes.js";
import invoicesRoutes from "../../../modules/invoices/invoices.routes.js";
import quotationsRoutes from "../../../modules/quotations/quotations.routes.js";
import ledgerRoutes from "../../../modules/ledger/ledger.routes.js";
import paymentsRoutes from "../../../modules/ledger/payments.routes.js";
import routesRoutes from "../../../modules/routes/routes.routes.js";
import routeTemplatesRoutes from "../../../modules/route-templates/routeTemplates.routes.js";
import subscriptionsRoutes from "../../../modules/subscriptions/subscriptions.routes.js";
import reportsRoutes from "../../../modules/reports/reports.routes.js";
import notificationsRoutes from "../../../modules/notifications/notifications.routes.js";
import inventoryRoutes from "../../../modules/inventory/inventory.routes.js";
import filesRoutes from "../../../modules/files/files.routes.js";
import lookupsRoutes from "../../../modules/lookups/lookups.routes.js";
import uiRoutes from "../../../modules/ui/ui.routes.js";
import auditRoutes from "../../../modules/audit/audit.routes.js";
import settingsRoutes from "../../../modules/settings/settings.routes.js";
import documentsRoutes from "../../../modules/documents/documents.routes.js";

const router = Router();

router.use("/system", systemRoutes);
router.use("/auth", authRoutes);
router.use("/vendors", vendorsRoutes);
router.use("/customers", customersRoutes);
router.use("/categories", categoriesRoutes);
router.use("/products", productsRoutes);
router.use("/orders", ordersRoutes);
router.use("/invoices", invoicesRoutes);
router.use("/quotations", quotationsRoutes);
router.use("/ledger", ledgerRoutes);
router.use("/payments", paymentsRoutes);
router.use("/routes", routesRoutes);
router.use("/route-templates", routeTemplatesRoutes);
router.use("/subscriptions", subscriptionsRoutes);
router.use("/reports", reportsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/files", filesRoutes);
router.use("/lookups", lookupsRoutes);
router.use("/ui", uiRoutes);
router.use("/audit", auditRoutes);
router.use("/settings", settingsRoutes);
router.use("/public/documents", documentsRoutes);

export default router;
